feat[Order]: CRUD
pawland-team/Pawland-BE pull request #7
Opened 2024-04-19 11:19 UTC by cmong0516

## 🛠️주요 변경 사항
-Order Crud

## 📣리뷰어가 꼭 알아야 하는 사항
- 구체적인 디자인이 나오면 세부적인 수정이 필요할거같아서 기본적인 CRUD 만 구현해 두었습니다!

## ❗관련이슈
- closed: #

## 🖼️스크린샷(선택)

2024-04-19 13:48 UTC, midcondria requested changes
고생하셨습니다!
빌드 실패 관련 부분 코멘트 남겼으니 확인 부탁드립니다!

2024-04-19 13:48 UTC, midcondria commented on src/main/java/com/pawland/order/controller/OrderController.java
> +    }
이 두개의 HTTP Method와 엔드포인트가 똑같아서 빌드 실패하는걸로 보입니다!

2024-04-19 13:48 UTC, midcondria commented on src/main/java/com/pawland/order/domain/OrderStatus.java
> +    PROCEEDING("진행중");
만약 추가한다면 CANCELED("취소")도 있으면 좋을것 같습니다.
주문 쪽은 프론트 쪽에서 포트원에서 만들어둔 API를 상당부분 이용할것 같아요.
[https://developers.portone.io/api/rest-v2/auth](url) 링크는 이쪽입니다.
주문 관련 부분은 프론트분과 상의하셔서 백엔드 API를 어떻게 만들지 이야기 나눠보시면 좋을것 같습니다!

2024-04-19 13:48 UTC, midcondria commented on src/main/java/com/pawland/order/service/OrderService.java
> +    }
이런 조회 메서드는 @Transactional(readonly=true) 를 붙이는걸 추천드립니다.
[https://hungseong.tistory.com/74](url) 이런 글을 참고해보셔도 좋을것 같습니다 ㅎㅎ
그래서 저는 서비스 레이어 최상단에 @Transactional(readonly=true)를 붙여두고 명령 메서드에는 따로 @Transactional을 붙이는 편입니다!

2024-04-19 13:48 UTC, midcondria commented on src/main/java/com/pawland/order/domain/Order.java
> +    }
:thumbsup:

2024-04-19 13:48 UTC, midcondria commented on src/main/java/com/pawland/order/service/OrderService.java
> +    }
사소한 부분이지만 public 메서드는 private 메서드들 위쪽으로 올려주시면 읽기 편하지 않을까 하는 생각이 들어요:)

2024-04-19 13:48 UTC, midcondria commented on src/main/java/com/pawland/product/domain/Product.java
>      private List<String> imageUrls = new ArrayList<>();
값 타입 컬랙션을 쓰시는군요
예전에 JPA 공부할 때 값 타입 컬렉션은 수정 시 컬렉션 내 모든 값을 지우고 다시 넣어서 1:* 관계를 쓰는게 좋다는 말을 본것 같은데 어떻게 생각하시는지 궁금합니다!

2024-04-19 13:48 UTC, midcondria commented on src/main/java/com/pawland/order/domain/OrderStatus.java
> +    }
아마 지금 IllegalArgumentException를 처리하는 ExceptionHandler가 없던걸로 기억해요.
IllegalArgumentException의 예외 처리도 추가해주시면 좋을것 같습니다 ㅎㅎ

2024-04-19 20:35 UTC, cmong0516 commented on src/main/java/com/pawland/order/controller/OrderController.java
> +    }
그렇네요 거래완료와 취소를 각각 엔드포인트를 분리해서 적용하는게 깔끔하겠죠 ?!

2024-04-19 20:35 UTC, cmong0516 commented on src/main/java/com/pawland/order/domain/OrderStatus.java
> +    PROCEEDING("진행중");
넵 상품이 아니라 주문 이니까 취소도 포함하도록 하겠습니다!

2024-04-19 20:39 UTC, cmong0516 commented on src/main/java/com/pawland/order/service/OrderService.java
> +    }
조회만을 위해 사용하는 메서드에 readOnly 를 적용해서 변경감지를 하지 않아서 성능이 올라갈수 있는거군요!
readonly 를 전체 서비스에 붙여두고 더티체킹이 필요한 경우에만 @Transactional 을 붙이는게 제일 간편한 방법일것 같네요 좋은정보 감사합니다!

2024-04-19 20:39 UTC, cmong0516 commented on src/main/java/com/pawland/order/service/OrderService.java
> +    }
넵 정리하면 확실히 보기 좋을거같습니다!

2024-04-19 20:40 UTC, cmong0516 commented on src/main/java/com/pawland/product/domain/Product.java
>      private List<String> imageUrls = new ArrayList<>();
이미지 부분이라 수정하기 로직이 좀 까다로울것 같아서 전부 지우고 다시 넣을 생각을 하고 있습니다!

2024-04-19 20:40 UTC, cmong0516 commented on src/main/java/com/pawland/order/domain/OrderStatus.java
> +    }
Exception 부분은 깔끔하게 한번에 정리할 생각입니다!
추후 각각 알맞은 Exception 으로 변경해두겠습니다 :)

2024-04-20 00:12 UTC, midcondria commented on src/main/java/com/pawland/order/controller/OrderController.java
> +    }
그게 깔끔할것 같습니다 ㅎㅎ

2024-04-20 00:13 UTC, midcondria approved these changes

2024-04-20 13:32 UTC, merged